//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANTORIUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURS
    {
        public int Id { get; set; }
        public int IdUSINIK { get; set; }
        public int IdPREPOD { get; set; }
    
        public virtual PREPOD PREPOD { get; set; }
        public virtual USINIK USINIK { get; set; }
    }
}
